#!/bin/sh

# Enable cookie persistent storage
export WPE_SHELL_COOKIE_STORAGE=1

# FIXME: gst-gl's dispmanx backend is messing up with our compositor
# when it creates its initial 16x16px surface.
export GST_GL_WINDOW=dummy

# Use cairo noaa compositor
#export CAIRO_GL_COMPOSITOR=noaa

# WebInspector
export WEBKIT_INSPECTOR_SERVER=0.0.0.0:9998

# FPS
#export WPE_THREADED_COMPOSITOR_FPS=1

# RPI mouse support
#export WPE_BCMRPI_CURSOR=1

# RPI touch support
export WPE_BCMRPI_TOUCH=1

# Core dumps
#echo 1 > /proc/sys/kernel/core_uses_pid
#echo 2 > /proc/sys/fs/suid_dumpable
#echo "/root/cores/core-pid_%p--process%E" > /proc/sys/kernel/core_pattern
#mkdir -p /root/cores
#ulimit -c unlimited

ulimit -n 100000
ulimit -s 65536
ulimit -l 512

if [ "$1" = "--loop" ];
then
	export HOME=/root
	mkdir -p $HOME
	while true;
	do
		cd /root && gobred-wpe "$2"
	done
else
	cd /root && gobred-wpe "$1"
fi
