#!/bin/sh

GOBRED_URL="file:///var/www/index.html"

start() {
	echo -n "Starting gobred: "
	/usr/bin/gobred --loop $GOBRED_URL &> /var/log/gobred &
	echo "OK"
}

stop() {
	echo -n "Stopping gobred: "
	killall gobred-wpe &> /dev/null
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
